name: Deploy Flask App to GitHub Container Registry

on:
  push:
    tags:
      - 'testv*'  # Triggers on tags starting with 'testv'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        env:
          CR_PAT: ${{ secrets.GITHUB_TOKEN }} 
        run: echo $CR_PAT | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ secrets.YOUR_GITHUB_USERNAME }}/qtell:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          IMAGE_NAME: ghcr.io/${{ secrets.YOUR_GITHUB_USERNAME }}/qtell:latest
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{
            "clearCache": "clear",
            "imageUrl": "'"${IMAGE_NAME}"'"
          }'
