name: Deploy Flask App to Render

on:
  push:
    tags:
      - 'testv*'  # This triggers the workflow for tags starting with 'testv'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Render
        uses: docker/login-action@v2
        with:
          registry: registry.render.com
          username: _  # Render uses `_` as username
          password: ${{ secrets.RENDER_API_KEY }}

      - name: Build and push Docker image
        run: |
          docker build -t registry.render.com/YOUR_RENDER_USERNAME/YOUR_SERVICE_NAME:latest .
          docker push registry.render.com/YOUR_RENDER_USERNAME/YOUR_SERVICE_NAME:latest

      - name: Trigger Render Deployment
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: YOUR_SERVICE_ID
        run: |
          curl -X POST "https://api.render.com/v1/deploys" \
          -H "Content-Type: application/json" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -d '{
            "serviceId": "'"$RENDER_SERVICE_ID"'"
          }'
